### ISSUE TITLE
compatability issue with node versions

### ISSUE THREAD

**Issue by harshitj2005** [shobhitmshr002/node-messageq#1]
npm WARN notsup Unsupported engine for node-messageq@0.0.5: wanted: {"node":"8.1.x","npm":"5.6.x"} (current: {"node":"12.14.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: node-messageq@0.0.5
npm WARN notsup Unsupported engine for node-messageq@0.0.2: wanted: {"node":"8.1.x","npm":"5.6.x"} (current: {"node":"12.14.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: node-messageq@0.0.2

**Comment by shobhitmshr002** [comment]
This is fixed in  [PR](https://github.com/shobhitmshr002/node-messageq/pull/2)
